'use client';

import { motion } from 'framer-motion';
import { Download, Plus, Home } from 'lucide-react';
import Link from 'next/link';
import { TravelersInfoFormData, useTravelersInfoStore } from '@/store/travelers-info-store';
import { DayItinerary } from '@/components/features/generate-trip/day-card';
import jsPDF from 'jspdf';

interface ConfirmationSuccessProps {
    formData: TravelersInfoFormData;
    destination: string;
    durationDays: number;
    itinerary: DayItinerary[];
}

export function ConfirmationSuccess({ formData, destination, durationDays, itinerary }: ConfirmationSuccessProps) {
    const resetForm = useTravelersInfoStore((state) => state.resetForm);
    const bookingId = `UT-${destination.substring(0, 3).toUpperCase()}-${new Date().getFullYear()}-001`;

    // Format dates
    const formatDate = (date: Date | null | string) => {
        if (!date) return '';
        const d = new Date(date);
        return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    };

    const dateRange = formData.startDate && formData.endDate
        ? `${formatDate(formData.startDate)}-${formatDate(formData.endDate)}, ${new Date(formData.endDate).getFullYear()}`
        : 'Date pending';

    const handleNewTrip = () => {
        resetForm();
    };

    const generatePDF = () => {
        const doc = new jsPDF();
        let yPos = 20;

        // Title
        doc.setFontSize(22);
        doc.setTextColor(0, 0, 0);
        doc.text(`Trip Itinerary: ${destination}`, 20, yPos);
        yPos += 15;

        // Trip Details
        doc.setFontSize(12);
        doc.setTextColor(100, 100, 100);
        doc.text(`Booking ID: ${bookingId}`, 20, yPos);
        yPos += 8;
        doc.text(`Dates: ${dateRange}`, 20, yPos);
        yPos += 8;
        doc.text(`Travelers: ${formData.travelerCounts.adults} Adults, ${formData.travelerCounts.children} Children`, 20, yPos);
        yPos += 8;
        doc.text(`Duration: ${durationDays} Days, ${Math.max(0, durationDays - 1)} Nights`, 20, yPos);
        yPos += 15;

        // Separator
        doc.setDrawColor(200, 200, 200);
        doc.line(20, yPos, 190, yPos);
        yPos += 15;

        // Itinerary Content
        doc.setTextColor(0, 0, 0);

        itinerary.forEach((day) => {
            // Check for page break
            if (yPos > 270) {
                doc.addPage();
                yPos = 20;
            }

            // Day Header
            doc.setFontSize(14);
            doc.setFont("helvetica", "bold");
            doc.text(`Day ${day.day}: ${day.title}`, 20, yPos);
            yPos += 8;

            // Activities
            doc.setFontSize(11);
            doc.setFont("helvetica", "normal");

            day.activities.forEach((activity) => {
                // Handle long text wrapping
                const splitText = doc.splitTextToSize(`• ${activity}`, 170);

                // Check if activity fits on page
                if (yPos + (splitText.length * 6) > 280) {
                    doc.addPage();
                    yPos = 20;
                }

                doc.text(splitText, 25, yPos);
                yPos += (splitText.length * 6) + 2;
            });

            yPos += 5; // Spacing between days
        });

        // Footer
        const pageCount = doc.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(10);
            doc.setTextColor(150, 150, 150);
            doc.text('Generated by UrbanTrips AI', 20, 285);
            doc.text(`Page ${i} of ${pageCount}`, 170, 285);
        }

        return doc;
    };

    const handleDownloadItinerary = () => {
        const doc = generatePDF();
        doc.save(`itinerary-${destination.replace(/\s+/g, '-').toLowerCase()}.pdf`);
    };

    const handleShareItinerary = async () => {
        try {
            const doc = generatePDF();
            const blob = doc.output('blob');
            const file = new File([blob], `itinerary-${destination.replace(/\s+/g, '-').toLowerCase()}.pdf`, { type: 'application/pdf' });

            const shareData = {
                title: `Trip Itinerary: ${destination}`,
                text: `Check out my travel plan for ${destination}!`,
                files: [file]
            };

            if (navigator.share && navigator.canShare && navigator.canShare(shareData)) {
                await navigator.share(shareData);
            } else {
                // Fallback for browsers that don't support sharing files
                handleDownloadItinerary();
            }
        } catch (error) {
            // Ignore AbortError (user cancelled)
            if (error instanceof Error && error.name !== 'AbortError') {
                console.error('Error sharing itinerary:', error);
            }
        }
    };

    return (
        <div className="flex flex-col items-center justify-center min-h-screen bg-white px-4 py-16">
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="text-center w-full max-w-md"
            >
                <h1 className="text-3xl font-bold text-black mb-1" style={{ fontFamily: 'var(--font-poppins), sans-serif' }}>
                    You&apos;re All Set!
                </h1>
                <h2 className="text-xl font-bold text-yellow-500 mb-6" style={{ fontFamily: 'var(--font-poppins), sans-serif' }}>
                    Your Plan is Confirmed!
                </h2>

                <p className="text-gray-600 text-sm mb-8 px-4">
                    Your travel itinerary has been saved. Our team will reach out soon.
                </p>

                {/* Details Card */}
                <div className="bg-gray-50 rounded-3xl p-6 mb-8 mx-2 border border-gray-100">
                    <h3 className="text-sm font-bold text-black mb-6 text-center" style={{ fontFamily: 'var(--font-poppins), sans-serif' }}>
                        Confirmation Details
                    </h3>

                    <div className="space-y-4">
                        <div className="flex justify-between items-center border-b border-gray-200 pb-3">
                            <span className="text-sm text-gray-500 font-medium">Booking ID</span>
                            <span className="text-sm font-bold text-black">{bookingId}</span>
                        </div>

                        <div className="flex justify-between items-center border-b border-gray-200 pb-3">
                            <span className="text-sm text-gray-500 font-medium">Destination</span>
                            <span className="text-sm font-bold text-black">{destination || 'Your Trip'}</span>
                        </div>

                        <div className="flex justify-between items-center border-b border-gray-200 pb-3">
                            <span className="text-sm text-gray-500 font-medium">Travel Dates</span>
                            <span className="text-sm font-bold text-black">{dateRange}</span>
                        </div>

                        <div className="flex justify-between items-center text-left">
                            <span className="text-sm text-gray-500 font-medium">Duration</span>
                            <span className="text-sm font-bold text-black">{durationDays} Days, {Math.max(0, durationDays - 1)} Nights</span>
                        </div>
                    </div>
                </div>

                {/* Actions */}
                <div className="space-y-3 mb-8 px-2">
                    <button
                        onClick={handleDownloadItinerary}
                        className="w-full bg-black text-white rounded-xl py-3.5 flex items-center justify-center gap-2 font-bold hover:bg-gray-900 transition-colors shadow-lg shadow-black/10"
                    >
                        <Download size={18} />
                        Download Itinerary
                    </button>

                    <div className="flex gap-3">
                        <Link href="/search" className="flex-1" onClick={handleNewTrip}>
                            <button className="w-full bg-yellow-400 text-black rounded-xl py-3.5 flex items-center justify-center gap-2 font-bold hover:bg-yellow-500 transition-colors shadow-lg shadow-yellow-400/20">
                                <Plus size={18} />
                                New Trip
                            </button>
                        </Link>

                        <Link href="/" className="flex-1">
                            <button className="w-full bg-white border border-gray-200 text-gray-500 rounded-xl py-3.5 flex items-center justify-center gap-2 font-bold hover:bg-gray-50 transition-colors">
                                <Home size={18} />
                                Home
                            </button>
                        </Link>
                    </div>
                </div>

                <button
                    onClick={handleShareItinerary}
                    className="text-black font-bold text-sm hover:underline"
                >
                    Share Itinerary
                </button>
            </motion.div>
        </div>
    );
}
